version: "3.1"

services:
   portainer:
     image: portainer/portainer 
     ports:
       - "443:9000"
     command: --ssl --sslcert /certs/portainer.crt --sslkey /certs/portainer.key
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /data/portainer:/data
       - /data/portainer/certs:/certs
     deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - "node.role == manager"
